server:
  port: 10083
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://192.168.0.111:3306/mall?characterEncoding=UTF-8&useSSL=false
    username: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

logging:
  level:
    cup.com.mapper: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10081/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10