server:
  port: 10086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /mall
    username: guest
    password: guest
    host: 127.0.0.1

sms:
  accessKeyId: JWffwFJIwada # 你自己的accessKeyId
  accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ # 你自己的AccessKeySecret
  signName: 乐优商城 # 签名名称
  verifyCodeTemplate: SMS_133976814 # 模板名称